name: CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  dotnetapp:
  
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        working-directory: ./Test.Services
        dotnet-version: 3.1.301
    - name: Install dependencies
      working-directory: ./Test.Services
      run: dotnet restore
    - name: Build
      working-directory: ./Test.Services
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: ./Test.Services
      run: dotnet test --no-build --verbosity normal

  angularapp:

    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.15.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Set SSC false
      run: npm config set strict-ssl false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set SSL false
      working-directory: ./Dashboard.UI
      run: npm set strict-ssl false
    - name: Install dependencies
      working-directory: ./Dashboard.UI
      run: npm ci
    - name: Build
      working-directory: ./Dashboard.UI
      run: npm run build 
